app:
  customer-service-uri: "http://localhost:6060"
  product-service-uri: "http://localhost:7070"
  external-service-timeout: 3
apps:
  greeting: Welcome to The Testing Aggregator Service From The Config Server
